module Promise {
  fun reject (input : a) : Promise(a, b) {
    ``
  }
}

component Main {
  fun test : Promise(Never, String) {
    sequence {
      greeting =
        Promise.reject("x")

      b =
        Promise.reject("y")

      a =
        Promise.reject(0)

      "blah"
    } catch String => a {
      "hello"
    } catch Number => a {
      "asd"
    }
  }

  fun render : Html {
    try {
      test()

      <div/>
    }
  }
}
--------------------------------------------------------------------------------
const $Promise = new(class extends Module {
  reject(input) {
    return
  }
})

class $Main extends Component {
  test() {
    return (async () => {
      let _result = null;

      try {
        let greeting = await (async () => {
          try {
            return await $Promise.reject(`x`)
          } catch (_error) {
            let a = _error;

            _result = `hello`

            throw new DoError()
          }
        })()

        let b = await (async () => {
          try {
            return await $Promise.reject(`y`)
          } catch (_error) {
            let a = _error;

            _result = `hello`

            throw new DoError()
          }
        })()

        let a = await (async () => {
          try {
            return await $Promise.reject(0)
          } catch (_error) {
            let a = _error;

            _result = `asd`

            throw new DoError()
          }
        })()

        _result = await `blah`
      } catch (_error) {
        if (_error instanceof DoError) {} else {
          console.warn(`Unhandled error in sequence expression:`)
          console.warn(_error)
        }
      }

      return _result
    })()
  }

  render() {
    return (() => {
      this.test()

      return _createElement("div", {})
    })()
  }
}

$Main.displayName = "Main"
