module Result {
  fun error (input : a) : Result(a, b) {
    `new Err(input)`
  }
}

component Main {
  fun test : Promise(Never, String) {
    sequence {
      Result.error("")

      "test"
    } catch String => error {
      "test"
    }
  }

  fun render : Html {
    try {
      test()

      <div/>
    }
  }
}
--------------------------------------------------------------------------------
const $Result = new(class extends Module {
  error(input) {
    return new Err(input)
  }
})

class $Main extends Component {
  test() {
    return (async () => {
      let _result = null;

      try {
        let _0 = $Result.error(``)

        if (_0 instanceof Err) {
          let _error = _0.value

          let error = _error;

          _result = `test`

          throw new DoError()
        }

        _0.value

        _result = await `test`
      } catch (_error) {
        if (_error instanceof DoError) {} else {
          console.warn(`Unhandled error in sequence expression:`)
          console.warn(_error)
        }
      }

      return _result
    })()
  }

  render() {
    return (() => {
      this.test()

      return _createElement("div", {})
    })()
  }
}

$Main.displayName = "Main"
